const fighterTab = {
    ants: [
		{
			name: { a: 'Giant Ant', b: '巨蟻' },
			symbol: 'a',
			color: colorList.acid,
			race: ANIMAL,
			mod: NORMAL,
			grade: NORMAL,
			lvl: 8,
			rarity: 0,
			hpRate: -10,
			mpRate: 0,
			str: 10,
			dex: 10,
			con: 5,
			int: 5,
			spd: -50,
			dmgBase: 10,
			acBase: 50,
			dmgAcid: 10,
			group: true,
			dropNum: 0,
			matDropRate: 3,
			material: M_SHELL,
			atkType: AT_T,
		},
	],

    bats: [
		{
			name: { a: 'Giant Bat', b: '大蝙蝠' },
			symbol: 'b',
			color: colorList.gray,
			race: ANIMAL,
			mod: NORMAL,
			grade: NORMAL,
			lvl: 4,
			rarity: 0,
			hpRate: -9,
			mpRate: 0,
			str: 5,
			dex: 20,
			con: 10,
			int: 5,
			spd: 50,
			dmgBase: 10,
			acBase: 20,
			stealLife: 30,
			dropNum: 0,
			matDropRate: 3,
			material: M_FEATHER,
			atkType: AT_T,
			grow: DEX,
		},
	],

    canines: [
		{
            name: { a: 'She-wolf', b: '雌狼' },
            symbol: 'c',
            color: colorList.brown,
            race: ANIMAL,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 1,
            rarity: 0,
            hpRate: -10,
            mpRate: 0,
            str: 5,
            dex: 10,
            con: 5,
            int: 5,
            spd: 0,
            dmgBase: 10,
            acBase: 25,
            frw: 20,
            dropNum: 0,
            matDropRate: 2,
            material: M_FUR,
            atkType: AT_S,
            grow: DEX,
		},
		
        {
            name: { a: 'Laelaps, the Hound of Cephalus', b: '狩人ケパロスの猟犬ラエラプス' },
            symbol: 'c',
            color: colorList.brown,
            race: ANIMAL,
            mod: UNIQUE,
            grade: NORMAL,
            lvl: 20,
            rarity: 30,
            hpRate: -2,
            mpRate: 0,
            str: 40,
            dex: 80,
            con: 30,
            int: 25,
            spd: 25,
            dmgBase: 70,
            acBase: 100,
            frw: 100,
            dropNum: 2,
            matDropRate: 0,
            material: M_FUR,
            atkType: AT_S | AT_T,
            skillProb: 1 / 6,
            skill: {
				a: { id: RAID, lvl: 5 },
            },

            desc: {
                a:'',
                b:'女神アルテミスより授与された、どんな獲物も逃がさないとされる猟犬。同じく、どんな追手にも捕まらないという狐と膠着状態となり、ゼウスにより両者は石に変えられる。',
            }
        },
	],
	
    felines: [
		{
            name: { a: 'Lion', b: '獅子' },
            symbol: 'f',
            color: colorList.yellow,
            race: ANIMAL,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 13,
            rarity: 0,
            hpRate: -4,
            mpRate: 0,
            str: 25,
            dex: 30,
            con: 25,
            int: 5,
            spd: 25,
            dmgBase: 30,
            acBase: 80,
            dropNum: 0,
            matDropRate: 2,
            material: M_FUR,
            atkType: AT_S | AT_T,
            grow: STR
		},
		
        {
            name: { a: 'Nemean lion', b: 'ネメアの獅子' },
            symbol: 'f',
            color: colorList.yellow,
            race: ANIMAL,
            mod: UNIQUE,
            grade: NORMAL,
            lvl: 21,
            rarity: 30,
            hpRate: 0,
            mpRate: 0,
            str: 50,
            dex: 50,
            con: 30,
            int: 25,
            spd: 25,
            dmgBase: 75,
            acBase: 250,
            acRed: 25,
            earth: 50,
            frw: 50,
            dropNum: 2,
            matDropRate: 0,
            material: M_FUR,
            atkType: AT_S | AT_T,
            skillProb: 1 / 5,
            skill: {
				a: { id: RAID, lvl: 5 },
            },

            desc: {
                a:'',
                b:'ネメアの谷に住む獅子。その毛皮は棍棒や矢では傷付かないが、ヘラクレスに手づかみにされ絞殺される。',
            }
        },
	],
	
    golems: [
		{
            name: { a: 'Golem', b: 'ゴーレム' },
            symbol: 'g',
            color: null,
            race: GIANT,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 14,
            rarity: 0,
            hpRate: 0,
            mpRate: 0,
            str: 30,
            dex: 10,
            con: 25,
            int: 5,
            spd: -50,
            dmgBase: null,
            acBase: null,
            piece: true,
            volumeRate: 1,
            dropNum: 0,
            matDropRate: 2,
            material: M_STONE,
            atkType: AT_B,
            grow: CON,
		},
		
        // {
        //     name: { a: 'Golem', b: 'ゴーレム' },
        //     symbol: 'g',
        //     color: null,
        //     race: GIANT,
        //     mod: NORMAL,
        //     grade: NORMAL,
        //     lvl: 20,
        //     rarity: 10,
        //     hpRate: 2,
        //     mpRate: 0,
        //     str: 10,
        //     dex: 3,
        //     con: 10,
        //     int: 1,
        //     spd: 0,
        //     dmgBase: null,
        //     acBase: null,
        //     dropNum: 0,
        //     matDropRate: 2,
        //     material: M_METAL,
        //     atkType: AT_T,
        //     grow: CON,
        //     volumeRate: 2
		// },
		
        // {
        //     name: { a: 'Golem', b: 'ゴーレム' },
        //     symbol: 'g',
        //     color: null,
        //     race: GIANT,
        //     mod: NORMAL,
        //     grade: NORMAL,
        //     lvl: 30,
        //     rarity: 20,
        //     hpRate: 2,
        //     mpRate: 0,
        //     str: 10,
        //     dex: 3,
        //     con: 10,
        //     int: 1,
        //     spd: 10,
        //     dmgBase: null,
        //     acBase: null,
        //     dropNum: 0,
        //     matDropRate: 2,
        //     material: M_GEM,
        //     atkType: AT_S,
        //     grow: CON,
        //     volumeRate: 3
        // },
	],
	
    humanoids: [
		{
            name: { a: 'Incarnation', b: '化身' },
            symbol: 'h',
            color: colorList.white,
            race: GOD,
            mod: RARE,
            grade: NORMAL,
            lvl: 25,
            rarity: 0,
            hpRate: 0,
            mpRate: 0,
            str: 50,
            dex: 50,
            con: 50,
            int: 50,
            spd: 25,
            dmgBase: 100,
            acBase: 100,
            fire: 30,
            water: 30,
            air: 30,
            earth: 30,
            poison: 30,
            dropNum: 3,
            matDropRate: 1,
            atkType: AT_B,
        },

        {
            name: { a: 'Calypso, the Sea Goddess', b: '海の女神カリュプソ' },
            symbol: 'h',
            color: colorList.blue,
            race: GOD,
            mod: UNIQUE,
            grade: NORMAL,
            lvl: 30,
            rarity: 30,
            hpRate: 0,
            mpRate: 0,
            str: 150,
            dex: 150,
            con: 150,
            int: 150,
            spd: 100,
            dmgBase: 200,
            acBase: 200,
            water: 100,
            strSus: true,
            dexSus: true,
            conSus: true,
            intSus: true,
            dropNum: 4,
            matDropRate: 0,
            atkType: AT_B,
            skillProb: 1 / 4,
            skill: { 
				a: { id: ICE_BOLT, lvl: 10 },
				b: { id: HEAL, lvl: 10 },
				c: { id: AQUA_BREATH, lvl: 10 }
            },

            desc: {
                a:'',
                b:'巨人アトラスの娘、仙女。海に漂流したオデュッセウスを救護し、7年間孤島で共に暮す。',
            }
        },
	],
	
    incubuses: [
		{
			name: { a: 'Incubuses', b: '夢魔' },
			symbol: 'i',
			color: colorList.gray,
			race: DEMON,
			mod: NORMAL,
			grade: NORMAL,
			lvl: 26,
			rarity: 0,
			hpRate: 0,
			mpRate: 0,
			str: 50,
			dex: 75,
			con: 50,
			int: 50,
			spd: 50,
			dmgBase: 70,
			acBase: 100,
			stealMana: 30,
			levi: true,
			awake: true,
			dropNum: 2,
			matDropRate: 2,
			material: M_SKIN,
			atkType: AT_S,
		},
	],

    mimics: [
		{
			name: { a: 'Mimic', b: 'ミミック' },
			symbol: 'm',
			color: colorList.brown,
            race: null,
			mod: NORMAL,
			grade: NORMAL,
			lvl: 10,
			rarity: 0,
			hpRate: -10,
			mpRate: 0,
			str: 25,
			dex: 25,
			con: 5,
			int: 5,
			spd: 0,
			dmgBase: 75,
			acBase: 50,
			stillness: true,
            canAttack: true,
			awake: true,
			mimic: true,
			dropNum: 1,
			matDropRate: 1,
			atkType: AT_B,
		},
	],

    persons: [
		{
            name: { a: 'Warrior', b: '戦士' },
            symbol: 'p',
            color: colorList.brown,
            race: HUMAN,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 7,
            rarity: 0,
            hpRate: 2,
            mpRate: 0,
            str: 15,
            dex: 10,
            con: 10,
            int: 5,
            spd: 0,
            dmgBase: 1,
            acBase: 0,
            dropNum: 1,
            matDropRate: 2,
            material: M_BONE,
            atkType: AT_B,
            grow: STR,
            starter: [
				{ type: 'melee', tabId: M_CLUB },
				{ type: 'armor', tabId: A_ARMOR }
			]
		},
		
        {
            name: { a: 'Hunter', b: '狩人' },
            symbol: 'p',
            color: colorList.red,
            race: HUMAN,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 10,
            rarity: 0,
            hpRate: -2,
            mpRate: 0,
            str: 10,
            dex: 20,
            con: 10,
            int: 10,
            spd: 0,
            dmgBase: 1,
            acBase: 0,
            dropNum: 1,
            matDropRate: 2,
            material: M_BONE,
            atkType: AT_B,
            grow: DEX,
            starter: [
				{ type: 'missile', tabId: M_BOW },
				{ type: 'ammo', tabId: A_ARROW },
				{ type: 'armor', tabId: A_VEST },
				{ type: 'melee', tabId: M_KNIFE, side: 'a' }
			]
		},
		
        {
            name: { a: 'Magus', b: '魔術師' },
            symbol: 'p',
            color: colorList.purple,
            race: HUMAN,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 15,
            rarity: 0,
            hpRate: -5,
            mpRate: 2,
            str: 5,
            dex: 5,
            con: 5,
            int: 10,
            spd: 0,
            dmgBase: 1,
            acBase: 0,
            dropNum: 2,
            matDropRate: 2,
            skillProb: 1 / 5,
            skill: { 
				a: { id: FIRE_BOLT, lvl: 10 },
				b: { id: SHORT_TELEPORTATION, lvl: 1 }
			},

            material: M_BONE,
            atkType: AT_B,
            grow: INT,
            starter: [
				{ type: 'staff', tabId: S_STAFF },
				{ type: 'armor', tabId: A_ROBE }
			]
		},
		
        {
            name: { a: 'Thief', b: '盗賊' },
            symbol: 'p',
            color: colorList.gray,
            race: HUMAN,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 20,
            rarity: 0,
            hpRate: 0,
            mpRate: 0,
            str: 25,
            dex: 50,
            con: 25,
            int: 25,
            spd: 25,
            dmgBase: 1,
            acBase: 0,
            atkStealItem: 20,
            atkStealGold: 20,
            stealth: 25,
            dropNum: 2,
            matDropRate: 2,
            material: M_BONE,
            atkType: AT_B,
            grow: DEX,
            starter: [
				{ type: 'melee', tabId: M_DAGGER },
				{ type: 'armor', tabId: A_VEST }
			]
		},
		
        {
            name: { a: 'Iros, the Beggar', b: '乞食イロス' },
            symbol: 'p',
            color: colorList.brown,
            race: HUMAN,
            mod: UNIQUE,
            grade: NORMAL,
            lvl: 5,
            rarity: 30,
            hpRate: -8,
            mpRate: 0,
            str: 10,
            dex: 10,
            con: 10,
            int: 10,
            spd: 0,
            dmgBase: 1,
            acBase: 0,
            atkStealItem: 20,
            dropNum: 1,
            matDropRate: 0,
            material: M_BONE,
            atkType: AT_B,
            starter: [
                { type: 'staff', tabId: S_STICK, matBase: M_WOOD, matId: WOOD_CYPRESS },
                { type: 'armor', tabId: A_ROBE, matBase: M_CLOTH, matId: CLOTH_LINEN }
            ],

            desc: {
                a:'',
                b:'イタケの町を徘徊する土着の乞食。同業に対して頭面をしていたが、乞食に扮したオデュッセウスと格闘の末打ち据えられる。',
            }
		},
		
        {
            name: { a: 'Dolon, the Spy', b: '偵察者ドロン' },
            symbol: 'p',
            color: colorList.bronze,
            race: HUMAN,
            mod: UNIQUE,
            grade: NORMAL,
            lvl: 10,
            rarity: 30,
            hpRate: -2,
            mpRate: 0,
            str: 35,
            dex: 40,
            con: 30,
            int: 25,
            spd: 50,
            dmgBase: 1,
            acBase: 0,
            dropNum: 1,
            matDropRate: 0,
            material: M_BONE,
            atkType: AT_B,
            skillProb: 1 / 10,
            skill: {
				a: { id: SHORT_TELEPORTATION, lvl: 1 },
				b: { id: TELEPORTATION, lvl: 1 }
            },

            starter: [
                { type: 'missile', tabId: M_BOW, matBase: M_WOOD, matId: WOOD_CYPRESS },
                { type: 'melee', tabId: M_SPEAR, matBase: M_METAL, matId: METAL_BRONZE, side: 'a' },
                { type: 'cloak', tabId: C_COAT, matBase: M_FUR, matId: FUR_WOLF },
                { type: 'helm', tabId: H_CAP, matBase: M_FUR, matId: FUR_FERRET },
                { type: 'ammo', tabId: A_ARROW },
            ],

            desc: {
                a:'',
                b:'伝令使エウメデスの子、トロイア人。ギリシャ軍の偵察任務を買って出たが捕らわれる。尋問の後、懇願するもディオメデスにより殺される。',
            }
		},
		
        {
            name: { a: 'Pandarus, the Archer of Troy', b: 'トロイアの射手パンダロス' },
            symbol: 'p',
            color: colorList.bronze,
            race: HUMAN,
            mod: UNIQUE,
            grade: NORMAL,
            lvl: 22,
            rarity: 30,
            hpRate: 0,
            mpRate: 0,
            str: 50,
            dex: 100,
            con: 50,
            int: 50,
            spd: 50,
            dmgBase: 1,
            acBase: 0,
            dexSus: true,
            dropNum: 2,
            matDropRate: 0,
            material: M_BONE,
            atkType: AT_B,
            starter: [
				{ type: 'missile', tabId: M_BOW, uniqueId: 0 },
				{ type: 'ammo', tabId: A_ARROW },
				{ type: 'melee', tabId: M_SPEAR, matBase: M_METAL, matId: METAL_BRONZE, side: 'a' },
				{ type: 'armor', tabId: A_ARMOR, matBase: M_METAL, matId: METAL_BRONZE },
			],

            skillProb: 1 / 8,
            skill: {
				a: { id: SHORT_TELEPORTATION, lvl: 1 },
				b: { id: ENCOURAGEMENT, lvl: 1 }
			},

            desc: {
                a:'',
                b:'ゼレイア王リュカオンの子。メネラウスに急所を射る矢を放つも、アテネにより防がれ、同じく庇護を受けたディオメデスの槍で息絶える。',
            }
		},
		
        {
            name: { a: 'Nestor, the Knight of Gerenia', b: 'ゲレニアの騎士ネストル' },
            symbol: 'p',
            color: colorList.bronze,
            race: HUMAN,
            mod: UNIQUE,
            grade: NORMAL,
            lvl: 29,
            rarity: 30,
            hpRate: 2,
            mpRate: 0,
            str: 100,
            dex: 100,
            con: 100,
            int: 125,
            spd: 50,
            dmgBase: 1,
            acBase: 0,
            ias: 50,
            strSus: true,
            dexSus: true,
            conSus: true,
            dropNum: 2,
            matDropRate: 0,
            material: M_BONE,
            atkType: AT_B,
            skillProb: 1 / 6,
            skill: {
				a: { id: RUSH, lvl: 5 },
				b: { id: SPEED, lvl: 5 }
            },

            starter: [
				{ type: 'melee', tabId: M_SWORD, matBase: M_METAL, matId: METAL_BRONZE },
				{ type: 'melee', tabId: M_SPEAR, matBase: M_METAL, matId: METAL_BRONZE, side: 'a' },
				{ type: 'shield', tabId: S_SHIELD, matBase: M_METAL, matId: METAL_GOLD, magic: true },
				{ type: 'armor', tabId: A_ARMOR, matBase: M_METAL, matId: METAL_BRONZE },
				{ type: 'cloak', tabId: C_CLOAK, matBase: M_CLOTH, matId: CLOTH_WOOL },
				{ type: 'belt', tabId: B_SASH, matBase: M_CLOTH, matId: CLOTH_WOOL },
				{ type: 'helm', tabId: H_HELM, matBase: M_METAL, matId: METAL_BRONZE },
				{ type: 'boots', tabId: B_SHOES, matBase: M_CLOTH, matId: CLOTH_WOOL },
            ],

            desc: {
                a:'',
                b:'ネレウスの子、ピュロスの王、ギリシャ軍の武将。老齢期にトロイア戦争に参加、助言・相談役を果たす。',
            }
		},
		
        {
            name: { a: 'Orlando, the Frenzy', b: '狂乱のオルランド' },
            symbol: 'p',
            color: colorList.orange,
            race: HUMAN,
            mod: UNIQUE,
            grade: NORMAL,
            lvl: 32,
            rarity: 30,
            hpRate: 6,
            mpRate: 0,
            str: 150,
            dex: 100,
            con: 150,
            int: 1,
            spd: 100,
            dmgBase: 50,
            acBase: 50,
            ias: 100,
            frw: 100,
            strSus: true,
            dexSus: true,
            conSus: true,
            awake: true,
            dropNum: 4,
            matDropRate: 0,
            material: M_BONE,
            atkType: AT_B,
            desc: {
                a:'',
                b:'シャルルマーニュの甥、聖騎士。思い人のアンジェリカが他妻となり発狂。その怪力で自身の鎧ごと衣服を引き裂き、分別なく暴れ狂う。',
            }
        },
	],
	
    quadrupeds: [
        {
            name: { a: 'Boar', b: '猪' },
            symbol: 'q',
            color: colorList.brown,
            race: ANIMAL,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 2,
            rarity: 0,
            hpRate: -8,
            mpRate: 0,
            str: 5,
            dex: 5,
            con: 10,
            int: 5,
            spd: 0,
            dmgBase: 20,
            acBase: 25,
            dropNum: 0,
            matDropRate: 2,
            material: M_FUR,
            atkType: AT_B,
            grow: CON
		},
		
		{
            name: { a: 'Horse', b: '馬' },
            symbol: 'q',
            color: colorList.orange,
            race: ANIMAL,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 3,
            rarity: 0,
            hpRate: -9,
            mpRate: 0,
            str: 10,
            dex: 15,
            con: 5,
            int: 5,
            spd: 0,
            dmgBase: 15,
            acBase: 25,
            frw: 100,
            dropNum: 0,
            matDropRate: 2,
            material: M_SKIN,
            atkType: AT_B,
            grow: DEX
		},
		
        {
            name: { a: 'Rays of the Sun, the Horse of Rhesus', b: 'トラキア王レソスの馬 `陽光の矢`' },
            symbol: 'q',
            color: colorList.white,
            race: ANIMAL,
            mod: UNIQUE,
            grade: NORMAL,
            lvl: 12,
            rarity: 30,
            hpRate: 0,
            mpRate: 0,
            str: 25,
            dex: 35,
            con: 25,
            int: 25,
            spd: 50,
            dmgBase: 30,
            acBase: 100,
            frw: 100,
            dropNum: 2,
            matDropRate: 0,
            material: M_SKIN,
            atkType: AT_B,
            desc: {
                a:'',
                b:'トラキア産の駿馬。大型で、雪よりも白く、走る速さは風にも劣らない。トロイア軍から奪った際、ネストルはこの馬を見て感嘆し、陽光の矢と評する。',
            }
		},
		
        {
            name: { a: 'Calydonian Boar', b: 'カリュドーンの大猪' },
            symbol: 'q',
            color: colorList.brown,
            race: ANIMAL,
            mod: UNIQUE,
            grade: NORMAL,
            lvl: 23,
            rarity: 30,
            hpRate: 2,
            mpRate: 0,
            str: 100,
            dex: 50,
            con: 100,
            int: 50,
            spd: 25,
            dmgBase: 150,
            acBase: 100,
            frw: 50,
            matDropRate: 0,
            dropNum: 2,
            material: M_FUR,
            atkType: AT_B,
            skillProb: 1 / 6,
            skill: {
				a: { id: RUSH, lvl: 5 },
            },

            desc: {
                a:'',
                b:'女神アルテミスがカリュドーンの町に放った大猪。辺り一帯を荒すが、青年期のネストルを含む勇士達により討伐される。',
            }
        },
	],
	
    skeletons: [
		{
			name: { a: 'Skeleton', b: 'スケルトン' },
			symbol: 's',
			color: null,
			race: UNDEAD,
			mod: NORMAL,
			grade: NORMAL,
			lvl: 3,
			rarity: 0,
			hpRate: -9,
			mpRate: 0,
			str: 5,
			dex: 5,
			con: 5,
			int: 5,
			spd: 0,
			dmgBase: null,
			acBase: null,
            piece: true,
			volumeRate: 1,
			dropNum: 0,
			matDropRate: 3,
			material: M_BONE,
			atkType: AT_B,
		},
	],

    worms: [
		{
			name: { a: 'Giant Worm', b: '大芋虫' },
			symbol: 'w',
			color: colorList.white,
			race: ANIMAL,
			mod: NORMAL,
			grade: NORMAL,
			lvl: 1,
			rarity: 0,
			hpRate: -15,
			mpRate: 0,
			str: 1,
			dex: 1,
			con: 1,
			int: 1,
			spd: -100,
			dmgBase: null,
			acBase: null,
			atkSlow: 20,
			group: true,
            piece: true,
			volumeRate: 0.5,
			dropNum: 0,
			matDropRate: 3,
			material: M_CLOTH,
			atkType: AT_B,
		},
	],

    zombies: [
		{
			name: { a: 'Living Bush', b: '生ける繁み' },
			symbol: 'z',
			color: colorList.gray,
			race: UNDEAD,
			mod: NORMAL,
			grade: NORMAL,
			lvl: 5,
			rarity: 0,
			hpRate: -8,
			mpRate: 0,
			str: 1,
			dex: 1,
			con: 1,
			int: 1,
			spd: -100,
			dmgBase: null,
			acBase: null,
			atkInf: 20,
			group: true,
            piece: true,
			volumeRate: 0.5,
			dropNum: 0,
			matDropRate: 3,
			material: M_WOOD,
			atkType: AT_B,
		},
	],

    angels: [
		{
			name: { a: 'Fallen Angel', b: '堕天使' },
			symbol: 'A',
			color: colorList.shadow,
			race: DEMON,
			mod: NORMAL,
			grade: NORMAL,
			lvl: 28,
			rarity: 0,
			hpRate: 2,
			mpRate: 2,
			str: 50,
			dex: 50,
			con: 50,
			int: 100,
			spd: 50,
			dmgBase: 100,
			acBase: 150,
			air: 50,
			levi: true,
			dropNum: 2,
			matDropRate: 1,
			material: M_FEATHER,
			atkType: AT_B,
			skillProb: 1 / 5,
			skill: {
				a: { id: HEAL, lvl: 10 },
				b: { id: SPEED, lvl: 10 },
				c: { id: BLESSING, lvl: 10 }
			}
		},
	],

    birds: [
		{
            name: { a: 'Eagle', b: '鷲' },
            symbol: 'B',
            color: colorList.shadow,
            race: ANIMAL,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 1,
            rarity: 0,
            hpRate: -10,
            mpRate: 0,
            str: 1,
            dex: 20,
            con: 1,
            int: 5,
            spd: 50,
            dmgBase: 15,
            acBase: 5,
            air: 30,
            levi: true,
            dropNum: 0,
            matDropRate: 2,
            material: M_FEATHER,
            atkType: AT_T,
            grow: DEX
		},
		
        {
            name: { a: 'Aedon, the Nightingale', b: '夜鶯アエドン' },
            symbol: 'B',
            color: colorList.yellowgreen,
            race: ANIMAL,
            mod: UNIQUE,
            grade: NORMAL,
            lvl: 15,
            rarity: 30,
            hpRate: -6,
            mpRate: 0,
            str: 25,
            dex: 50,
            con: 50,
            int: 25,
            spd: 100,
            dmgBase: 25,
            acBase: 50,
            air: 30,
            levi: true,
            awake: true,
            dropNum: 3,
            matDropRate: 0,
            material: M_FEATHER,
            atkType: AT_S | AT_T,
            skillProb: 1 / 8,
            skill: {
				a: { id: WIND_BREATH, lvl: 5 },
				b: { id: SCREAM, lvl: 5 }
            },

            desc: {
                a:'',
                b:'パンダレオスの娘。ニオベに多くの子がいる事を妬み、子の殺害を試みるが、自身の子を誤って殺害。悲しみに泣き暮れる様をゼウスが夜鶯の姿に変化させる。',
            }
		},
		
        {
            name: { a: 'Nisos, the White-tailed Eagle', b: '尾白鷲ニソス' },
            symbol: 'B',
            color: colorList.shadow,
            race: ANIMAL,
            mod: UNIQUE,
            grade: NORMAL,
            lvl: 27,
            rarity: 30,
            hpRate: -6,
            mpRate: 0,
            str: 50,
            dex: 100,
            con: 50,
            int: 50,
            spd: 50,
            dmgBase: 100,
            acBase: 50,
            air: 30,
            ias: 25,
            levi: true,
            dropNum: 4,
            matDropRate: 0,
            material: M_FEATHER,
            atkType: AT_S | AT_T,
            skillProb: 1 / 6,
            skill: {
				a: { id: RAID, lvl: 10 },
            },

            desc: {
                a:'',
                b:'メガラの王。娘スキュラが敵将に恋慕し、父を殺し国を差し出すも拒まれ、海に飛び込む。その後鳥の姿となるが、同じく大鷲と化した父ニソスが復讐を狙う。',
            }
        },
	],
	
    chimeras: [
		{
            name: { a: 'Chimera', b: 'キメラ' },
            symbol: 'C',
            color: null,
            race: ANIMAL,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 12,
            rarity: 0,
            hpRate: -5,
            mpRate: 0,
            str: 25,
            dex: 25,
            con: 25,
            int: 25,
            spd: 50,
            dmgBase: null,
            acBase: null,
            piece: true,
            volumeRate: 1,
            dropNum: 1,
            matDropRate: 2,
            material: M_SKIN,
            atkType: AT_T,
		},
		
        // {
        //     name: { a: 'Chimera', b: 'キメラ' },
        //     symbol: 'C',
        //     color: null,
        //     race: ANIMAL,
        //     mod: NORMAL,
        //     grade: NORMAL,
        //     lvl: 20,
        //     rarity: 10,
        //     hpRate: -1,
        //     mpRate: 0,
        //     str: 2,
        //     dex: 5,
        //     con: 2,
        //     int: 2,
        //     spd: 10,
        //     dmgBase: null,
        //     acBase: null,
        //     water: 20,
        //     dropNum: 1,
        //     matDropRate: 2,
        //     material: M_FUR,
        //     atkType: AT_B,
        //     volumeRate: 1.5
		// },
		
        // {
        //     name: { a: 'Chimera', b: 'キメラ' },
        //     symbol: 'C',
        //     color: null,
        //     race: ANIMAL,
        //     mod: NORMAL,
        //     grade: NORMAL,
        //     lvl: 30,
        //     rarity: 20,
        //     hpRate: -1,
        //     mpRate: 0,
        //     str: 2,
        //     dex: 5,
        //     con: 2,
        //     int: 2,
        //     spd: 20,
        //     dmgBase: null,
        //     acBase: null,
        //     air: 20,
        //     dropNum: 1,
        //     matDropRate: 2,
        //     levi: true,
        //     material: M_FEATHER,
        //     atkType: AT_S,
        //     volumeRate: 2
        // },
	],
	
    dragons: [
		{
            name: { a: 'Dragon', b: '竜' },
            symbol: 'D',
            color: colorList.green,
            race: DRAGON,
            mod: MAGIC,
            grade: NORMAL,
            lvl: 24,
            rarity: 0,
            hpRate: 4,
            mpRate: 0,
            str: 40,
            dex: 40,
            con: 40,
            int: 40,
            spd: 25,
            dmgBase: 60,
            acBase: 200,
            fire: 10,
            water: 10,
            air: 10,
            earth: 10,
            poison: 10,
            dropNum: 4,
            matDropRate: 1,
            material: M_SCALE | M_BONE | M_HORN,
            matMain: M_SCALE,
            atkType: AT_S | AT_T | AT_B,
            grow: CON
		},
		
        {
            name: { a: 'Dragon, the Never-sleeping', b: '眠らずの竜' },
            symbol: 'D',
            color: colorList.green,
            race: DRAGON,
            mod: UNIQUE,
            grade: NORMAL,
            lvl: 28,
            rarity: 30,
            hpRate: 4,
            mpRate: 1,
            str: 150,
            dex: 100,
            con: 150,
            int: 50,
            spd: 50,
            dmgBase: 200,
            acBase: 250,
            fire: 10,
            water: 10,
            air: 10,
            earth: 10,
            poison: 45,
            conSus: true,
            awake: true,
            dropNum: 6,
            matDropRate: 0,
            material: M_SCALE,
            atkType: AT_S | AT_T | AT_B,
            skillProb: 1 / 5,
            skill: {
				a: { id: POISON_BREATH, lvl: 10 }
            },

            desc: {
                a:'',
                b:'神ヘルメスがもたらした金羊毛を守護する。メデイアの魔法薬により、眠らないとされるこの竜が昏睡し、その間にイアソンは金羊毛を奪取する。',
            }
        },
	],
	
    elementals: [
		{
			name: { a: 'Elemental', b: '精霊' },
			symbol: 'E',
			color: colorList.white,
			race: SPIRIT,
			mod: RARE,
			grade: NORMAL,
			lvl: 5,
			rarity: 0,
			hpRate: -8,
			mpRate: 1,
			str: 1,
			dex: 1,
			con: 1,
			int: 25,
			spd: 0,
			dmgBase: 15,
			acBase: 25,
			fire: 20,
			water: 20,
			air: 20,
			earth: 20,
			poison: 20,
			moveRnd: true,
			dropNum: 0,
			matDropRate: 3,
			atkType: AT_S,
			skillProb: 1 / 5,
		},
	],

    fairies: [
		{
			name: { a: 'Fairy', b: '妖精' },
			symbol: 'F',
			color: colorList.lime,
			race: SPIRIT,
			mod: NORMAL,
			grade: NORMAL,
			lvl: 6,
			rarity: 0,
			hpRate: -6,
			mpRate: 0,
			str: 1,
			dex: 25,
			con: 1,
			int: 15,
			spd: 50,
			dmgBase: 1,
			acBase: 25,
			atkStealGold: 25,
			fire: 10,
			water: 10,
			air: 10,
			earth: 10,
			poison: 10,
			levi: true,
			moveRnd: true,
			dropNum: 0,
			matDropRate: 2,
			material: M_FEATHER,
			atkType: AT_S,
			grow: DEX
		},
	],

    ghosts: [
		{
			name: { a: 'Phantom', b: '亡者' },
			symbol: 'G',
			color: colorList.skyblue,
			race: UNDEAD,
			mod: NORMAL,
			grade: NORMAL,
			lvl: 15,
			rarity: 0,
			hpRate: -8,
			mpRate: 0,
			str: 15,
			dex: 35,
			con: 10,
			int: 15,
			spd: 0,
			dmgBase: 25,
			acBase: 5,
			levi: true,
			invisible: true,
			moveRnd: true,
			dropNum: 0,
			matDropRate: 2,
			atkType: AT_B,
		},
	],

    hybrids: [
		{
            name: { a: 'Snake Woman', b: '蛇女' },
            symbol: 'H',
            color: colorList.green,
            race: HUMAN | ANIMAL,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 8,
            rarity: 0,
            hpRate: -7,
            mpRate: 0,
            str: 20,
            dex: 20,
            con: 20,
            int: 10,
            spd: 0,
            dmgBase: 20,
            acBase: 50,
            poison: 30,
            atkCon: 20,
            dropNum: 1,
            matDropRate: 2,
            material: M_SCALE,
            atkType: AT_B,
        },
        
		{
            name: { a: 'Harpy', b: 'ハーピー' },
            symbol: 'H',
            color: colorList.skyblue,
            race: HUMAN | ANIMAL,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 9,
            rarity: 0,
            hpRate: -7,
            mpRate: 0,
            str: 10,
            dex: 30,
            con: 10,
            int: 10,
            spd: 25,
            dmgBase: 20,
            acBase: 80,
            air: 30,
            levi: true,
            dropNum: 1,
            matDropRate: 2,
            material: M_FEATHER,
            atkType: AT_S | AT_T,
            grow: DEX,
            skillProb: 1 / 10,
            skill: {
				a: { id: SCREAM, lvl: 5 }
			}
		},
		
        {
            name: { a: 'Centaur', b: 'ケンタウロス' },
            symbol: 'H',
            color: colorList.yellow,
            race: HUMAN | ANIMAL,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 23,
            rarity: 0,
            hpRate: 2,
            mpRate: 0,
            str: 40,
            dex: 75,
            con: 50,
            int: 25,
            spd: 25,
            dmgBase: 70,
            acBase: 100,
            frw: 75,
            dexSus: true,
            dropNum: 3,
            matDropRate: 1,
            material: M_BONE,
            atkType: AT_B,
            grow: DEX,
            starter: [
				{ type: 'missile', tabId: M_BOW },
				{ type: 'ammo', tabId: A_ARROW }
			]
		},
		
        {
            name: { a: 'Minotaur', b: 'ミノタウロス' },
            symbol: 'H',
            color: colorList.orange,
            race: HUMAN | ANIMAL,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 27,
            rarity: 0,
            hpRate: 2,
            mpRate: 0,
            str: 150,
            dex: 75,
            con: 75,
            int: 15,
            spd: 0,
            dmgBase: 120,
            acBase: 100,
            strSus: true,
            dropNum: 3,
            matDropRate: 1,
            material: M_BONE | M_HORN,
            matMain: M_HORN,
            atkType: AT_B,
            grow: STR,
            starter: [{ type: 'melee', tabId: M_TWO_HANDED_AXE }]
        },
	],
	
    nymphs: [
		{
			name: { a: 'Nymph', b: 'ニンフ' },
			symbol: 'N',
			color: colorList.olive,
			race: SPIRIT,
			mod: NORMAL,
			grade: NORMAL,
			lvl: 16,
			rarity: 0,
			hpRate: -6,
			mpRate: 0,
			str: 10,
			dex: 25,
			con: 15,
			int: 15,
			spd: 0,
			dmgBase: 15,
			acBase: 20,
			fire: 10,
			water: 10,
			air: 10,
			earth: 10,
			poison: 10,
			atkStealItem: 25,
			moveRnd: true,
			dropNum: 1,
			matDropRate: 2,
			atkType: AT_S,
		},
	],

    snakes: [
		{
            name: { a: 'Serpent', b: '大蛇' },
            symbol: 'J',
            color: colorList.purple,
            race: ANIMAL,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 3,
            rarity: 0,
            hpRate: -10,
            mpRate: 0,
            str: 5,
            dex: 10,
            con: 5,
            int: 5,
            spd: 0,
            dmgBase: 15,
            acBase: 30,
            poison: 30,
            dmgPoison: 10,
            dropNum: 0,
            matDropRate: 2,
            material: M_SCALE,
            atkType: AT_T,
		},
		
        {
            name: { a: 'Amphisbaena,the Serpent of the Two-headed', b: '双頭の大蛇`アンフィスバエナ`' },
            symbol: 'J',
            color: colorList.purple,
            race: ANIMAL,
            mod: UNIQUE,
            grade: NORMAL,
            lvl: 24,
            rarity: 30,
            hpRate: -4,
            mpRate: 0,
            str: 80,
            dex: 80,
            con: 50,
            int: 25,
            spd: 50,
            dmgBase: 100,
            acBase: 50,
            poison: 50,
            dmgPoison: 200,
            dropNum: 2,
            matDropRate: 0,
            material: M_SCALE,
            atkType: AT_T,
            skillProb: 1 / 6,
            skill: {
				a: { id: POISON_BREATH, lvl: 20 }
            },

            desc: {
                a:'',
                b:'リビアの砂漠に住むという双頭の毒蛇。ペルセウスが切り落とした、メデューサの首から落ちた血液により、この蛇は生まれたという。',
            }
        },
	],
	
    multiheads: [
		{
            name: { a: 'Hydra', b: 'ヒュドラ' },
            symbol: 'M',
            color: colorList.green,
            race: DRAGON,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 29,
            rarity: 0,
            hpRate: 4,
            mpRate: 0,
            str: 200,
            dex: 100,
            con: 200,
            int: 50,
            spd: 0,
            dmgBase: 30,
            acBase: 100,
            fire: -30,
            poison: 20,
            hpReg: 100,
            ias: 50,
            dmgPoison: 25,
            dropNum: 2,
            matDropRate: 1,
            material: M_SCALE,
            atkType: AT_T | AT_B,
            grow: CON,
            skillProb: 1 / 8,
            skill: {
				a: { id: POISON_BREATH, lvl: 10 }
			}
		},
		
        {
            name: { a: 'Scylla, the Sea-monster', b: '海の怪物スキュラ' },
            symbol: 'M',
            color: colorList.green,
            race: DRAGON,
            mod: UNIQUE,
            grade: NORMAL,
            lvl: 31,
            rarity: 80,
            hpRate: 4,
            mpRate: 0,
            str: 200,
            dex: 100,
            con: 200,
            int: 50,
            spd: 0,
            dmgBase: 50,
            acBase: 100,
            fire: -30,
            poison: 20,
            hpReg: 100,
            ias: 100,
            dmgPoison: 25,
            dropNum: 4,
            matDropRate: 0,
            material: M_SCALE,
            atkType: AT_T | AT_B,
            skillProb: 1 / 5,
            skill: {
				a: { id: AQUA_BREATH, lvl: 10 },
				b: { id: TELEPORT_TO, lvl: 1 }
            },

            desc: {
                a:'',
                b:'12本の足、6つの頭、3列に並んだ歯を持つ。元は女性であったが、グラウコスの求愛を拒み続け、それを妬んだキルケの毒により怪物に変貌する。',
            }
        },
	],
	
    giants: [
		{
            name: { a: 'Giant', b: '巨人' },
            symbol: 'P',
            color: colorList.yellow,
            race: GIANT,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 18,
            rarity: 0,
            hpRate: 3,
            mpRate: 0,
            str: 100,
            dex: 15,
            con: 30,
            int: 15,
            spd: -100,
            dmgBase: 100,
            acBase: 50,
            earth: 50,
            dropNum: 0,
            matDropRate: 1,
            material: M_BONE,
            atkType: AT_B,
            grow: CON
		},
		
        {
            name: { a: 'Cyclopes', b: 'サイクロプス' },
            symbol: 'P',
            color: colorList.orange,
            race: GIANT,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 21,
            rarity: 0,
            hpRate: 5,
            mpRate: 0,
            str: 100,
            dex: 50,
            con: 40,
            int: 15,
            spd: -100,
            dmgBase: 100,
            acBase: 50,
            earth: 50,
            dropNum: 0,
            matDropRate: 1,
            material: M_BONE,
            atkType: AT_B,
            grow: CON,
            starter: [
				{ type: 'missile', tabId: M_SLING },
				{ type: 'ammo', tabId: A_ROCK }
			]
		},
		
        {
            name: { a: 'Polyphemus,the One Eyed Giant', b: '隻眼の巨人ポリュペモス' },
            symbol: 'P',
            color: colorList.orange,
            race: GIANT,
            mod: UNIQUE,
            grade: NORMAL,
            lvl: 25,
            rarity: 30,
            hpRate: 5,
            mpRate: 0,
            str: 200,
            dex: 75,
            con: 200,
            int: 25,
            spd: -100,
            dmgBase: 300,
            acBase: 50,
            earth: 50,
            conSus: true,
            dropNum: 4,
            matDropRate: 0,
            material: M_BONE,
            atkType: AT_B,
            skillProb: 1 / 5,
            skill: {
				a: { id: CREATE_GIANT, lvl: 1 },
				b: { id: TELEPORT_TO, lvl: 1 }
            },

            desc: {
                a:'',
                b:'神ポセイドンの子、一つ目の巨人。洞窟内に閉じ込められたオデュッセウスは、この巨人が泥酔し寝ている間に、丸太を目に突き立て盲いにし脱出する。',
            }
        },
	],
	
    spiders: [
		{
            name: { a: 'Giant Spider', b: '大蜘蛛' },
            symbol: 'S',
            color: colorList.gray,
            race: ANIMAL,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 11,
            rarity: 0,
            hpRate: -6,
            mpRate: 0,
            str: 15,
            dex: 25,
            con: 10,
            int: 5,
            spd: 0,
            dmgBase: 25,
            acBase: 60,
            atkSlow: 20,
            dropNum: 0,
            matDropRate: 2,
            material: M_CLOTH,
            atkType: AT_T,
		},
		
        {
            name: { a: 'Giant Scorpion', b: '大サソリ' },
            symbol: 'S',
            color: colorList.brown,
            race: ANIMAL,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 17,
            rarity: 0,
            hpRate: -5,
            mpRate: 0,
            str: 15,
            dex: 25,
            con: 15,
            int: 5,
            spd: 0,
            dmgBase: 30,
            acBase: 120,
            atkPara: 10,
            dropNum: 0,
            matDropRate: 2,
            material: M_SHELL,
            atkType: AT_T,
        },
	],
	
    demons: [
		{
			name: { a: 'Demon', b: '悪魔' },
			symbol: 'U',
			color: colorList.gray,
			race: DEMON,
			mod: NORMAL,
			grade: NORMAL,
			lvl: 22,
			rarity: 0,
			hpRate: 4,
			mpRate: 0,
			str: 50,
			dex: 50,
			con: 50,
			int: 30,
			spd: 0,
			dmgBase: 80,
			acBase: 150,
			fire: 50,
			dropNum: 2,
			matDropRate: 1,
			material: M_SKIN | M_HORN,
            matMain: M_SKIN,
			atkType: AT_S | AT_B,
			skillProb: 1 / 8,
			skill: {
				a: { id: FIRE_BREATH, lvl: 10 },
				b: { id: ENCOURAGEMENT, lvl: 5 }
			}
		},
	],

    vampires: [
		{
			name: { a: 'Vampire', b: '吸血鬼' },
			symbol: 'V',
			color: colorList.gray,
			race: UNDEAD,
			mod: NORMAL,
			grade: NORMAL,
			lvl: 19,
			rarity: 0,
			hpRate: 0,
			mpRate: 0,
			str: 30,
			dex: 30,
			con: 30,
			int: 30,
			spd: 0,
			dmgBase: 40,
			acBase: 100,
			fire: -50,
			stealLife: 30,
			dropNum: 2,
			matDropRate: 2,
			material: M_BONE,
			atkType: AT_T,
		},
	],

    wraiths: [
		{
			name: { a: 'Wraith', b: '生霊' },
			symbol: 'W',
			color: colorList.gray,
			race: UNDEAD,
			mod: NORMAL,
			grade: NORMAL,
			lvl: 25,
			rarity: 0,
			hpRate: -2,
			mpRate: 0,
			str: 50,
			dex: 50,
			con: 25,
			int: 50,
			spd: 0,
			dmgBase: 50,
			acBase: 100,
			atkDrain: 50,
			dropNum: 2,
			matDropRate: 2,
			material: M_CLOTH | M_BONE,
            matMain: M_BONE,
			atkType: AT_T,
		},
	],

    statues: [
		{
            name: { a: 'Trap Statue ', b: '罠像' },
            symbol: '%',
            color: null,
            race: null,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 10,
            rarity: 0,
            hpRate: 0,
            mpRate: 0,
            str: 1,
            dex: 1,
            con: 1,
            int: 1,
            spd: 0,
            dmgBase: null,
            acBase: null,
            fire: 50,
            water: 50,
            air: 50,
            earth: 50,
            poison: 50,
            stillness: true,
            awake: true,
            piece: true,
            volumeRate: 1,
            dropNum: 0,
            matDropRate: 3,
            material: M_STONE | M_PLATING,
            atkType: AT_B,
            skillProb: 1 / 8,
            skill: {
				a: { id: CREATE_TRAP, lvl: 1 }
			}
		},
		
        {
            name: { a: 'Summon Statue', b: '召喚像' },
            symbol: '%',
            color: null,
            race: null,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 20,
            rarity: 0,
            hpRate: 0,
            mpRate: 0,
            str: 1,
            dex: 1,
            con: 1,
            int: 1,
            spd: 0,
            dmgBase: null,
            acBase: null,
            fire: 50,
            water: 50,
            air: 50,
            earth: 50,
            poison: 50,
            awake: true,
            stillness: true,
            piece: true,
            skillProb: 1 / 8,
            dropNum: 0,
            matDropRate: 3,
            material: M_STONE | M_PLATING,
            atkType: AT_B,
            volumeRate: 1,
            skill: {
				a: { id: CREATE_MONSTER, lvl: 1 }
			}
		},
		
        {
            name: { a: 'Gargoyle Statue', b: 'ガーゴイル像' },
            symbol: '%',
            color: null,
            race: DEMON,
            mod: MAGIC,
            grade: NORMAL,
            lvl: 30,
            rarity: 30,
            hpRate: 0,
            mpRate: 0,
            str: 50,
            dex: 50,
            con: 50,
            int: 50,
            spd: 0,
            dmgBase: null,
            acBase: null,
            fire: 50,
            water: 50,
            air: 50,
            earth: 50,
            poison: 50,
            stillness: true,
            canAttack: true,
            awake: true,
            piece: true,
            volumeRate: 1,
            dropNum: 0,
            matDropRate: 2,
            material: M_STONE | M_PLATING,
            atkType: AT_S,
        },
	],
	
    misc: [
		{
            name: { a: 'Rogue', b: 'ローグ' },
            symbol: '@',
            color: colorList.white,
            race: HUMAN,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 1,
            rarity: 0,
            hpRate: 0,
            mpRate: 0,
            str: 10,
            dex: 10,
            con: 10,
            int: 10,
            spd: 0,
            dmgBase: 1,
            acBase: 0,
            acSRate: 1,
            acTRate: 1,
            acBRate: 1,
            awake: true,
            dropNum: 0,
            matDropRate: 0,
            atkType: AT_B,
            starter: [
                { type: 'melee', tabId: M_DAGGER, starter: true },
                { type: 'armor', tabId: A_VEST, starter: true },
                { type: 'book', tabId: B_SPELL_1 },
                { type: 'book', tabId: B_SKILL_1 },
                { type: 'food', tabId: F_RATION, quantity: 5 },
                { type: 'light', tabId: L_TORCH, starter: true },
            ],
		},
		
        {
            name: { a: 'Yeti', b: 'イエティ' },
            symbol: 'Y',
            color: colorList.white,
            mod: NORMAL,
            grade: NORMAL,
            lvl: 1,
            rarity: 0,
            hpRate: 0,
            mpRate: 0,
            str: 1,
            dex: 1,
            con: 1,
            int: 1,
            spd: 0,
            dmgBase: 1,
            acBase: 1,
            acSRate: 1,
            acTRate: 1,
            acBRate: 1,
            dropNum: 0,
            matDropRate: 0,
            atkType: AT_B,
		},
		
        {
            name: { a: 'Beelzebub, the Lord of the Flies', b: '蝿の王ベルゼブブ' },
            symbol: 'U',
            color: colorList.gray,
            race: DEMON,
            mod: UNIQUE,
            grade: NORMAL,
            boss: true,
            lvl: 33,
            rarity: 0,
            hpRate: 4,
            mpRate: 5,
            str: 300,
            dex: 300,
            con: 200,
            int: 200,
            spd: 100,
            dmgBase: 150,
            acBase: 300,
            acSRate: 1,
            acTRate: 1,
            acBRate: 1,
            acRed: 50,
            fire: 20,
            water: 20,
            air: 20,
            earth: 20,
            poison: 20,
            dmgPoison: 100,
            levi: true,
            awake: true,
            strSus: true,
            dexSus: true,
            conSus: true,
            intSus: true,
            dropNum: 8,
            matDropRate: 0,
            atkType: AT_S | AT_T | AT_B,
            skillProb: 1 / 6,
            skill: {
				a: { id: COCYTUS, lvl: 20 },
				b: { id: POISON_BREATH, lvl: 5 },
				c: { id: INFECTION_BREATH, lvl: 5 },
				d: { id: CREATE_MAGIC_MONSTER, lvl: 1 }
            },

            desc: {
                a:'',
                b:'地獄の君主、十六の悪魔の指揮官、悪魔達の皇帝。人間を誘惑し嫉妬心を生み出す。しばしばサタンと同一視される。',
            }
        },
    ],
};

{
    let acTRateList = {
        golems: 2,
        statues: 1.5,
        chimeras: 1,
        skeletons: .7,
        zombies: .5,
        worms: .2,

        giants: 2,
        dragons: 1.9,
        multiheads: 1.8,
        demons: 1.7,
        vampires: 1.6,
        incubuses: 1.5,
        angels: 1.4,
        wraiths: 1.3,
        ghosts: 1.2,
        hybrids: 1.1,
        humanoids: 1,
        persons: 1,
        quadrupeds: .9,
        felines: .8,
        canines: .8,
        nymphs: .7,
        elementals: .7,
        fairies: .6,
        birds: .5,
        snakes: .4,
        spiders: .3,
        ants: .2,
        bats: .1,

        mimics: 1,
    };

    let getAcRate = (fighter) => {
        if (!fighter.material) return [1, 1];
        let mat = fighter.matMain ? fighter.matMain : fighter.material;
        let hRate = materialMap.get(mat).hRate;
        let mean = (1 + MAX_HARDNESS) / 2;
        let sRate = 1 + (hRate - mean) / 10;
        let bRate = 1 - (hRate - mean) / 10;
        return [sRate, bRate];
    }

    for (let key in fighterTab) {
        if (key === 'misc') continue;
        for (let fighter of fighterTab[key]) {
            if (fighter.acBase === null) continue;
            fighter.acTRate = acTRateList[key];
            [fighter.acSRate, fighter.acBRate] = getAcRate(fighter);
        }
    }
}

const fighterNumsMap = (() => {
    let nums = new Map();
    for (let key in fighterTab)
        nums.set(key, enums(0, fighterTab[key].length - 1));
    return nums;
})();

const FT = Object.keys(fighterTab);
